### PR TITLE
CS-BOS - and support for multi-OS versions

### LINKED ISSUE #32: app-request: Simple Shell-like launcher for old computer
The "modern" launcher is miss-placed on old computer. We need a simple command-line like launcher for them

### PR DESCRIPTION
**Pull request by bell07**
As requested, discussed and hacked in #32 
Closes #32

### CODE REVIEW

**Comment by Grizzly-Adam** [comment]
Im onboard. Happen to see this is ready.

**Comment by Gerold55** [comment]
I'll update the forums in a bit am working today so...

**Comment by Gerold55** [comment]
Forums has been updated except for the pics just removed old pics

**Comment by bell07** [comment]
You can write some words more about themes, OS-versions, printing, removables, Chess (new app) and the other things are developed in the meantime, see the updated README.md

By the way, I see the README.md needs an update acording new node names ...

**Comment by Grizzly-Adam** [comment]
It would be good to get pick of CS-BOS up there as well to show the versatility we are incorporating.

**Pull request merged**
