### PR TITLE
initial recipe_compat framework

### PR DESCRIPTION
**Pull request by bell07**
Be more flexible for #73 
This PR does nothing new but allow change recipes depending on installed mods.
It is an preparation for recipes without some mesecons mods but with homedecor for examle.

The idea is to add fallback mapping from default mod
silicon => group:sand for example. But this idea is still incomplete. 

At the first I look which Items I need to replace in recipes to be compatible with my whynot subgame

### CODE REVIEW

**Comment by Gerold55** [comment]
Sounds good to me.

**Comment by bell07** [comment]
Added recipe compatibility for homedecor items instead of mesecons gates, fpga and luacontroller to be compatible to the whynot game. If both mods (homedecor + mesecons_*) installed the mesecons items are used.  Of course additional ideas and mappings welcome. In order we can define the priorities. Ideally we need for all items fallback items from default mod.

By the way, the "floppy" needs more materials then the computer case, was slightly strange for me...

**Comment by Grizzly-Adam** [comment]
In real life floppies are a film disk with bits of a magnetic metal on them, covered in a plastic case. And, of course, there is a piece of aluminum the slides open and closed on 3 1/2" floppies. There are no electronics inside them.

**Comment by bell07** [comment]
My first computer used 8" floppies, so I know about the inside ;-)

The motor was the best mapping for "controller" for me. I think the "controller" is misplaced in mesecons recipe variant too for floppy.

**Comment by Grizzly-Adam** [comment]
I could make a seperate floppy drive component.

**Comment by bell07** [comment]
The separate floppy drive component needs an recipe too ;-)

At the end all own items needs to be crafteable by "default" items or by other often installed mods like homedecor, xdecor, technic, mesecons.

**Comment by Grizzly-Adam** [comment]
If you want to come up wuth recipes for 3.5" floppy drive, I will make you
textures.

**Comment by bell07** [comment]
Can this pull be merged or further ideas what should be added / changed / adjusted?

**Comment by Grizzly-Adam** [comment]
Im at work, havent been able to look at the pull.

**Comment by Grizzly-Adam** [comment]
Floppy texture is in my git as promised.

**Comment by bell07** [comment]
Did not found the file in any branch :-(

**Comment by Grizzly-Adam** [comment]
https://github.com/Grizzly-Adam/minetest-laptop/blob/recipe_compat/textures/laptop_floppydrive.png

**Comment by bell07** [comment]
I did not understand the idea for floppy drive. The issue was an component to craft floppy that is not motor or controller because the floppy does not have any electronic inside :-/

**Comment by Grizzly-Adam** [comment]
It is the drive that has the electronics inside. Should we make a
plastic/vinylpvc component to use in making of various media and computer
parts?

**Comment by bell07** [comment]
We need a recipe for electronic-less floppy item that is used to store data. Your critique was the homedecor motor item is misplaced, for me the  mesecons controller is misplaced too. So we need a more realistic idea how to craft the floppy

**Comment by Grizzly-Adam** [comment]
Floppies are 99 percent plastic and a little bit of magnetic metal. How do we make plastic? In the media pack I used a recipe of 8 obsidian shards and a steel ingot to make the 5.25" floppy disk.

**Comment by bell07** [comment]
I like the homedecor's plastic sheeting for "my variant". Do not know which item could be used from mesecons. Anything with the mesecons_materials:glue?

magnetic metal could be default:iron_lump.

**Comment by Grizzly-Adam** [comment]
That's good, I like that. The glue, not so much. Don't they have like a plastic coating for wires? Insulation?

**Comment by bell07** [comment]
> Insulation?
Cooked glue is mesecons_materials:fiber that is used for insulation

**Comment by Grizzly-Adam** [comment]
Fiber-- that's it.

**Comment by Grizzly-Adam** [comment]
Maybe use a combo of fiber and glue with iron lump for floppies. Refine the metal as the disks get bigger. For instance, 5.25" used iron lump. 3.5" could use steel ignot. Larger disks like zip drive or mini disk if we decide to make these could use steel cube.

**Comment by bell07** [comment]
A cube is 1 meter x 1 meter x 1 meter if placed.  Ok for computer case, but really to much for mini disk ;-)

**Comment by Grizzly-Adam** [comment]
I am imagining that it is compressed during the crafting process. You know how they are always fitting more components into smaller cases :)

**Comment by bell07** [comment]
https://youtu.be/Jn4k2TPIJf0

**Comment by Grizzly-Adam** [comment]
lol

**Comment by bell07** [comment]
rebased to current upstream

**Pull request merged**
