### PR TITLE
Grizzly-Adam themes revision

### PR DESCRIPTION
**Pull request by bell07**
Follow-up pull request replacing #98 and #100

### CODE REVIEW

**Comment by Grizzly-Adam** [comment]
If I am reading this right you are removing desktop_icon_label_button, exit_charactern and titlebar_textcolor???,

**Comment by bell07** [comment]
I just changed the order in "Freedom" theme and in API.md

**Comment by Grizzly-Adam** [comment]
Oh OK. Because we have themes using them :)

**Comment by bell07** [comment]
I am unhappy with Freedom as default. It should be an simple theme with less overrides in other themes. But this is maybe an other pull

**Comment by Grizzly-Adam** [comment]
Everything else looked good from what I could tell. And those background images-- are they mine? I spent about an hour reducing the size of all of them through limiting the pallets so the game loads faster.

**Comment by bell07** [comment]
I did not touched the images, just squashed all "delete file" and "add file" commits into one. But double-check it, maybe anything goes wrong with git

**Comment by Grizzly-Adam** [comment]
OK, looks like theme. I'm going to take it for a spin around the block.

**Comment by Grizzly-Adam** [comment]
It all looks good from here. I just ran through every theme. I think it is ready.

**Comment by bell07** [comment]
Should I click to "Merge pull request"?

**Comment by Grizzly-Adam** [comment]
I believe so.

**Comment by bell07** [comment]
Thank you for the great work!

**Comment by Grizzly-Adam** [comment]
Same to you. I am starting to understand you computers a bit better.

**Pull request merged**
