### PR TITLE
realchess app added

### PR DESCRIPTION
**Pull request by bell07**
As requested in #62

### CODE REVIEW

**Comment by bell07** [comment]
@Gerold55 @Grizzly-Adam please for testing and review. Can this app be merged as is?

**Comment by Grizzly-Adam** [comment]
It looked good to me. I say merge.

**Comment by bell07** [comment]
I am unsure about gameplay. I tried it in singleplayer only: Me vs. Me, and missed the "undo" button sometimes ;-(

**Comment by Grizzly-Adam** [comment]
I will try to get the old lady to play with me in a short while and see how it works. If she is feeling up to it.

**Comment by Gerold55** [comment]
Is this ready to be merged or no?

**Comment by Grizzly-Adam** [comment]
Hold on, I will give it a quick 2 player test. It fell off my radar when she wasn't well enough to test with me the day after her surgery.

**Comment by Gerold55** [comment]
Oh sorry to hear that 😞^

**Comment by Grizzly-Adam** [comment]
She had cancer removed from her forehead on Tuesday, which is why I  had time off and was on here so much this week.

@Gerold55 please see my update to PC Pack, it's just two lines but it will need to be merged when we release CS-BOS.

**Comment by Grizzly-Adam** [comment]
We very quickly ended up being able to move the pieces where ever we wanted, with no regard to the rules of the game.

**Comment by Gerold55** [comment]
@bell07

**Comment by bell07** [comment]
> Grizzly-Adam commented 20 hours ago
> We very quickly ended up being able to move the pieces where ever we wanted, with no regard to the rules of the game.

That is what I meant  :-(

@Grizzly-Adam ,did you tried the "original" already I copied the game from? https://github.com/minetest-mods/realchess
Unsure if it is my fault or I copied the bug from template. My initial idea was "just quickly reuse the code with some laptop-related adjustments". If the reused code is buggy anyone needs to take over the development, I am not a chess-player :-/

**Comment by Grizzly-Adam** [comment]
@bell07 I used the version included in xdecor. Chances are the bug carried over from the original version, but I couldn't recreate in on that board.

**Comment by bell07** [comment]
Compared the code from xdecor and realchess. Both is the same, so I am searching for my own bug now

**Comment by bell07** [comment]
Ok, found the bug, need to cut the "laptop:" from pieces names. @Grizzly-Adam, please try again if the game is playable now.

**Comment by Grizzly-Adam** [comment]
OK, give me a few. I will need to push an update to my server and the kids are playing on it.

**Comment by Grizzly-Adam** [comment]
On first move of the game, pawn can be moved anywhere in second row up. This is only for the first player.

**Comment by bell07** [comment]
Same behaviour in xdecor version?

**Comment by Grizzly-Adam** [comment]
Oh yep!!! It's not your bug!

**Comment by bell07** [comment]
Then you can open issue  for xdecor and/or for minetest-mods/realchess projects. Maybe an other developer can solve it. Or if you like, you can try to fix it, I think you know enough lua in meantime to do it ;-)

**Comment by bell07** [comment]
What's about this PR? Can we merge them despite the pawn bug in first step?

**Comment by Grizzly-Adam** [comment]
Yes, its not our bug.

**Pull request merged**
