### PR TITLE
Update README.md including credits

### PR DESCRIPTION
**Pull request by bell07**
Please do not merge directly, other credits needs to be assigned to other components I do not know.
If you do not know how to add them, just write to the comments and I update the change.

By the way, we need to check the Licenses if compatible if we use components from other people. I checked the tetris, in homedecor it is WTFPL too, is ok also.
What's about textures licenses? WTFPL is not usual for them.

### CODE REVIEW

**Comment by bell07** [comment]
You can update it byself, just use the edit button on
https://github.com/Gerold55/minetest-laptop/blob/bell07-README-Update/README.md
and use "preview changes" before saving

**Comment by Gerold55** [comment]
Fruit and bubbles were made by veNext. All of the rest were made by v-rob

**Comment by bell07** [comment]
Added veNext and v-rob to the themes authors, What about Hardware and items? Which parts are by Toby109tt, Cross_over and Yours?

**Comment by Gerold55** [comment]
Toby109tt and Cross_over made the icons. Cross_over and I made the PC/laptop nodes.

**Comment by bell07** [comment]
@Cross_over, @Gerold55, @Toby109tt, @v-rob @veNext, could you please check this information if all credits are assigned right and if I forgotten anything?
https://github.com/Gerold55/minetest-laptop/blob/bell07-README-Update/README.md

**Comment by Gerold55** [comment]
@CrossZover

**Comment by Gerold55** [comment]
@tobyplowy

**Comment by tobyplowy** [comment]
Yup that's good

**Comment by Crosszover** [comment]
Good!

**Comment by veNext** [comment]
looks good

**Comment by Gerold55** [comment]
@Bell07 are we able to send this pull request through?

**Comment by bell07** [comment]
Merged. If something wrong, we can adjust in second PR

**Pull request merged**
